apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wallet-reports.name" . }}
  labels:
  {{- include "wallet-reports.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "wallet-reports.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "wallet-reports.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wallet-reports.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "wallet-reports.imageRepositoryWithTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: public-api
              containerPort: 80
          {{- with .Values.containerPorts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.containerLivenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.containerLivenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.containerLivenessProbe.periodSeconds }}
            httpGet:
              path: /{{ .Values.appApiPathPrefix }}/health-check
              port: 80
          {{- end }}
          env:
            - name: VELMIE_WALLET_USERS_DB_PASS
              value: "{{ required ".Values.appEnv.usersDbPass is required! Make sure to provide it." .Values.appEnv.usersDbPass }}"
            - name: VELMIE_WALLET_USERS_DB_USER
              value: "{{ required ".Values.appEnv.usersDbUser is required! Make sure to provide it." .Values.appEnv.usersDbUser }}"
            - name: VELMIE_WALLET_USERS_DB_NAME
              value: "{{ required ".Values.appEnv.usersDbName is required! Make sure to provide it." .Values.appEnv.usersDbName }}"
            - name: VELMIE_WALLET_USERS_DB_PORT
              value: "{{ required ".Values.appEnv.usersDbPort is required! Make sure to provide it." .Values.appEnv.usersDbPort }}"
            - name: VELMIE_WALLET_USERS_DB_HOST
              value: "{{ required ".Values.appEnv.usersDbHost is required! Make sure to provide it." .Values.appEnv.usersDbHost }}"
            - name: VELMIE_WALLET_USERS_DB_DRIV
              value: "mysql"
            - name: VELMIE_WALLET_ACCOUNTS_DB_PASS
              value: "{{ required ".Values.appEnv.accountsDbPass is required! Make sure to provide it." .Values.appEnv.accountsDbPass }}"
            - name: VELMIE_WALLET_ACCOUNTS_DB_USER
              value: "{{ required ".Values.appEnv.accountsDbUser is required! Make sure to provide it." .Values.appEnv.accountsDbUser }}"
            - name: VELMIE_WALLET_ACCOUNTS_DB_NAME
              value: "{{ required ".Values.appEnv.accountsDbName is required! Make sure to provide it." .Values.appEnv.accountsDbName }}"
            - name: VELMIE_WALLET_ACCOUNTS_DB_PORT
              value: "{{ required ".Values.appEnv.accountsDbPort is required! Make sure to provide it." .Values.appEnv.accountsDbPort }}"
            - name: VELMIE_WALLET_ACCOUNTS_DB_HOST
              value: "{{ required ".Values.appEnv.accountsDbHost is required! Make sure to provide it." .Values.appEnv.accountsDbHost }}"
            - name: VELMIE_WALLET_ACCOUNTS_DB_DRIV
              value: "mysql"
            - name: VELMIE_WALLET_CURRENCIES_DB_PASS
              value: "{{ required ".Values.appEnv.currenciesDbPass is required! Make sure to provide it." .Values.appEnv.currenciesDbPass }}"
            - name: VELMIE_WALLET_CURRENCIES_DB_USER
              value: "{{ required ".Values.appEnv.accountsDbUser is required! Make sure to provide it." .Values.appEnv.accountsDbUser }}"
            - name: VELMIE_WALLET_CURRENCIES_DB_NAME
              value: "{{ required ".Values.appEnv.currenciesDbName is required! Make sure to provide it." .Values.appEnv.currenciesDbName }}"
            - name: VELMIE_WALLET_CURRENCIES_DB_PORT
              value: "{{ required ".Values.appEnv.currenciesDbPort is required! Make sure to provide it." .Values.appEnv.currenciesDbPort }}"
            - name: VELMIE_WALLET_CURRENCIES_DB_HOST
              value: "{{ required ".Values.appEnv.currenciesDbHost is required! Make sure to provide it." .Values.appEnv.currenciesDbHost }}"
            - name: VELMIE_WALLET_CURRENCIES_DB_DRIV
              value: "mysql"
            - name: VELMIE_WALLET_SETTINGS_DB_HOST
              value: "{{ required ".Values.appEnv.settingsDbHost is required! Make sure to provide it." .Values.appEnv.settingsDbHost }}"
            - name: VELMIE_WALLET_SETTINGS_DB_PORT
              value: "{{ required ".Values.appEnv.settingsDbPort is required! Make sure to provide it." .Values.appEnv.settingsDbPort }}"
            - name: VELMIE_WALLET_SETTINGS_DB_PASS
              value: "{{ required ".Values.appEnv.settingsDbPass is required! Make sure to provide it." .Values.appEnv.settingsDbPass }}"
            - name: VELMIE_WALLET_SETTINGS_DB_USER
              value: "{{ required ".Values.appEnv.settingsDbUser is required! Make sure to provide it." .Values.appEnv.settingsDbUser }}"
            - name: VELMIE_WALLET_SETTINGS_DB_NAME
              value: "{{ required ".Values.appEnv.settingsDbName is required! Make sure to provide it." .Values.appEnv.settingsDbName }}"
            - name: VELMIE_WALLET_SETTINGS_DB_DRIV
              value: "mysql"
            - name: PHP_INI_MEMORY_LIMIT
              value: "{{ .Values.phpIni.memoryLimit }}"
            - name: PHP_INI_MAX_EXECUTION_TIME
              value: "{{ .Values.phpIni.maxExecutionTime }}"
            - name: PHP_INI_MAX_INPUT_TIME
              value: "{{ .Values.phpIni.maxInputTime }}"
            - name: PHP_INI_DISPLAY_ERRORS
              value: "{{ .Values.phpIni.displayErrors }}"
            - name: PHP_INI_POST_MAX_SIZE
              value: "{{ .Values.phpIni.postMaxSize }}"
            - name: PHP_INI_FILE_UPLOADS
              value: "{{ .Values.phpIni.fileUploads }}"
            - name: PHP_INI_UPLOAD_MAX_FILESIZE
              value: "{{ .Values.phpIni.uploadMaxFilesize }}"
            - name: PHP_INI_MAX_FILE_UPLOADS
              value: "{{ .Values.phpIni.maxFileUploads }}"
            - name: PHP_OPCACHE_ENABLE
              value: "{{ .Values.phpIni.opcacheEnable }}"
            - name: PHP_OPCACHE_MEMORY_CONSUMPTION
              value: "{{ .Values.phpIni.opcacheMemoryConsumption }}"
            - name: PHP_OPCACHE_MAX_ACCELERATED_FILES
              value: "{{ .Values.phpIni.opcacheMaxAcceleratedFiles }}"
            - name: PHP_OPCACHE_MAX_WASTED_PERCENTAGE
              value: "{{ .Values.phpIni.opcacheMaxWastedPercentage }}"
            - name: PHP_OPCACHE_REVALIDATE_FREQ
              value: "{{ .Values.phpIni.opcacheRevalidateFreq }}"
            # TODO: get rid of hardcoded values (legacy) - use real service discovery
            - name: SERVICE_PERMISSIONS
              value: "http://wallet-permissions:12308"
            - name: SERVICE_USERS
              value: "http://wallet-users:12308"
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
