apiVersion: v1
kind: Service
metadata:
  name: {{ include "wallet-reports.name" . }}
  labels:
  {{- include "wallet-reports.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: public-api
      port: {{ required ".Values.service.ports.public is required! Make sure to provide it." .Values.service.ports.public }}
      targetPort: 80
  selector:
  {{- include "wallet-reports.selectorLabels" . | nindent 4 }}