# MySQL administrator credentials
# This user is used in order to perform tasks related to initialization such as for example
# creating DB schema (see hooks.dbInit)
mysqlAdmin:
    user: "root"
    password: "secret"

# Application environment variables
appEnv:
    # VELMIE_WALLET_REPORTS_CORS_METHODS
    corsMethods: "GET,POST,PUT,OPTIONS"
    # VELMIE_WALLET_REPORTS_CORS_ORIGINS
    corsOrigins: "*"
    # VELMIE_WALLET_REPORTS_CORS_HEADERS
    corsHeaders: "*"
    # VELMIE_WALLET_USERS_DB_PASS
    usersDbPass: ""
    # VELMIE_WALLET_USERS_DB_USER
    usersDbUser: ""
    # VELMIE_WALLET_USERS_DB_HOST
    usersDbHost: ""
    # VELMIE_WALLET_ACCOUNTS_DB_PASS
    accountsDbPass: ""
    # VELMIE_WALLET_ACCOUNTS_DB_USER
    accountsDbUser: ""
    # VELMIE_WALLET_ACCOUNTS_DB_HOST
    accountsDbHost: ""
    # VELMIE_WALLET_CURRENCIES_DB_PASS
    currenciesDbPass: ""
    # VELMIE_WALLET_CURRENCIES_DB_USER
    currenciesDbUser: ""
    # VELMIE_WALLET_CURRENCIES_DB_HOST
    currenciesDbHost: ""
    # VELMIE_WALLET_SETTINGS_DB_HOST
    settingsDbHost: ""
    # VELMIE_WALLET_SETTINGS_DB_PORT
    # VELMIE_WALLET_SETTINGS_DB_PASS
    settingsDbPass: ""
    # VELMIE_WALLET_SETTINGS_DB_USER
    settingsDbUser: ""