<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Velmie\Wallet\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>velmie.wallet.users.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 Id = 1;</code>
     */
    private $Id = 0;
    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     */
    private $Type = '';
    /**
     * Generated from protobuf field <code>string CountryIsoTwo = 3;</code>
     */
    private $CountryIsoTwo = '';
    /**
     * Generated from protobuf field <code>string Region = 4;</code>
     */
    private $Region = '';
    /**
     * Generated from protobuf field <code>string City = 5;</code>
     */
    private $City = '';
    /**
     * Generated from protobuf field <code>string ZipCode = 6;</code>
     */
    private $ZipCode = '';
    /**
     * Generated from protobuf field <code>string Address = 7;</code>
     */
    private $Address = '';
    /**
     * Generated from protobuf field <code>string AddressSecondLine = 8;</code>
     */
    private $AddressSecondLine = '';
    /**
     * Generated from protobuf field <code>string Name = 9;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>string PhoneNumber = 10;</code>
     */
    private $PhoneNumber = '';
    /**
     * Generated from protobuf field <code>string Description = 11;</code>
     */
    private $Description = '';
    /**
     * Generated from protobuf field <code>double Latitude = 12;</code>
     */
    private $Latitude = 0.0;
    /**
     * Generated from protobuf field <code>double Longitude = 13;</code>
     */
    private $Longitude = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Id
     *     @type string $Type
     *     @type string $CountryIsoTwo
     *     @type string $Region
     *     @type string $City
     *     @type string $ZipCode
     *     @type string $Address
     *     @type string $AddressSecondLine
     *     @type string $Name
     *     @type string $PhoneNumber
     *     @type string $Description
     *     @type float $Latitude
     *     @type float $Longitude
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 Id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>uint64 Id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CountryIsoTwo = 3;</code>
     * @return string
     */
    public function getCountryIsoTwo()
    {
        return $this->CountryIsoTwo;
    }

    /**
     * Generated from protobuf field <code>string CountryIsoTwo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryIsoTwo($var)
    {
        GPBUtil::checkString($var, True);
        $this->CountryIsoTwo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Region = 4;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->Region;
    }

    /**
     * Generated from protobuf field <code>string Region = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string City = 5;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->City;
    }

    /**
     * Generated from protobuf field <code>string City = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->City = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ZipCode = 6;</code>
     * @return string
     */
    public function getZipCode()
    {
        return $this->ZipCode;
    }

    /**
     * Generated from protobuf field <code>string ZipCode = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setZipCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ZipCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Address = 7;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->Address;
    }

    /**
     * Generated from protobuf field <code>string Address = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string AddressSecondLine = 8;</code>
     * @return string
     */
    public function getAddressSecondLine()
    {
        return $this->AddressSecondLine;
    }

    /**
     * Generated from protobuf field <code>string AddressSecondLine = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressSecondLine($var)
    {
        GPBUtil::checkString($var, True);
        $this->AddressSecondLine = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 9;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PhoneNumber = 10;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->PhoneNumber;
    }

    /**
     * Generated from protobuf field <code>string PhoneNumber = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->PhoneNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Description = 11;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * Generated from protobuf field <code>string Description = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->Description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double Latitude = 12;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->Latitude;
    }

    /**
     * Generated from protobuf field <code>double Latitude = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->Latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double Longitude = 13;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->Longitude;
    }

    /**
     * Generated from protobuf field <code>double Longitude = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->Longitude = $var;

        return $this;
    }

}

