<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Velmie\Wallet\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>velmie.wallet.users.BenificialOwner</code>
 */
class BenificialOwner extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string bo_full_name = 1;</code>
     */
    private $bo_full_name = '';
    /**
     * Generated from protobuf field <code>string bo_phone_number = 2;</code>
     */
    private $bo_phone_number = '';
    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_year = 3;</code>
     */
    private $bo_date_of_birth_year = 0;
    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_month = 4;</code>
     */
    private $bo_date_of_birth_month = 0;
    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_day = 5;</code>
     */
    private $bo_date_of_birth_day = 0;
    /**
     * Generated from protobuf field <code>string bo_document_personal_id = 6;</code>
     */
    private $bo_document_personal_id = '';
    /**
     * Generated from protobuf field <code>string bo_document_type = 7;</code>
     */
    private $bo_document_type = '';
    /**
     * Generated from protobuf field <code>string bo_address = 8;</code>
     */
    private $bo_address = '';
    /**
     * Generated from protobuf field <code>string bo_relationship = 9;</code>
     */
    private $bo_relationship = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bo_full_name
     *     @type string $bo_phone_number
     *     @type int|string $bo_date_of_birth_year
     *     @type int|string $bo_date_of_birth_month
     *     @type int|string $bo_date_of_birth_day
     *     @type string $bo_document_personal_id
     *     @type string $bo_document_type
     *     @type string $bo_address
     *     @type string $bo_relationship
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string bo_full_name = 1;</code>
     * @return string
     */
    public function getBoFullName()
    {
        return $this->bo_full_name;
    }

    /**
     * Generated from protobuf field <code>string bo_full_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBoFullName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bo_full_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bo_phone_number = 2;</code>
     * @return string
     */
    public function getBoPhoneNumber()
    {
        return $this->bo_phone_number;
    }

    /**
     * Generated from protobuf field <code>string bo_phone_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBoPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->bo_phone_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_year = 3;</code>
     * @return int|string
     */
    public function getBoDateOfBirthYear()
    {
        return $this->bo_date_of_birth_year;
    }

    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_year = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBoDateOfBirthYear($var)
    {
        GPBUtil::checkUint64($var);
        $this->bo_date_of_birth_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_month = 4;</code>
     * @return int|string
     */
    public function getBoDateOfBirthMonth()
    {
        return $this->bo_date_of_birth_month;
    }

    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_month = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBoDateOfBirthMonth($var)
    {
        GPBUtil::checkUint64($var);
        $this->bo_date_of_birth_month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_day = 5;</code>
     * @return int|string
     */
    public function getBoDateOfBirthDay()
    {
        return $this->bo_date_of_birth_day;
    }

    /**
     * Generated from protobuf field <code>uint64 bo_date_of_birth_day = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBoDateOfBirthDay($var)
    {
        GPBUtil::checkUint64($var);
        $this->bo_date_of_birth_day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bo_document_personal_id = 6;</code>
     * @return string
     */
    public function getBoDocumentPersonalId()
    {
        return $this->bo_document_personal_id;
    }

    /**
     * Generated from protobuf field <code>string bo_document_personal_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBoDocumentPersonalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->bo_document_personal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bo_document_type = 7;</code>
     * @return string
     */
    public function getBoDocumentType()
    {
        return $this->bo_document_type;
    }

    /**
     * Generated from protobuf field <code>string bo_document_type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setBoDocumentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->bo_document_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bo_address = 8;</code>
     * @return string
     */
    public function getBoAddress()
    {
        return $this->bo_address;
    }

    /**
     * Generated from protobuf field <code>string bo_address = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBoAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->bo_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bo_relationship = 9;</code>
     * @return string
     */
    public function getBoRelationship()
    {
        return $this->bo_relationship;
    }

    /**
     * Generated from protobuf field <code>string bo_relationship = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBoRelationship($var)
    {
        GPBUtil::checkString($var, True);
        $this->bo_relationship = $var;

        return $this;
    }

}

