<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Velmie\Wallet\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Devices
 *
 * Generated from protobuf message <code>velmie.wallet.users.Device</code>
 */
class Device extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ID = 1;</code>
     */
    private $ID = '';
    /**
     * Generated from protobuf field <code>string Pin = 2;</code>
     */
    private $Pin = '';
    /**
     * Generated from protobuf field <code>string PushToken = 3;</code>
     */
    private $PushToken = '';
    /**
     * Generated from protobuf field <code>string OsType = 4;</code>
     */
    private $OsType = '';
    /**
     * Generated from protobuf field <code>string CreatedAt = 5;</code>
     */
    private $CreatedAt = '';
    /**
     * Generated from protobuf field <code>string UpdatedAt = 6;</code>
     */
    private $UpdatedAt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ID
     *     @type string $Pin
     *     @type string $PushToken
     *     @type string $OsType
     *     @type string $CreatedAt
     *     @type string $UpdatedAt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ID = 1;</code>
     * @return string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>string ID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Pin = 2;</code>
     * @return string
     */
    public function getPin()
    {
        return $this->Pin;
    }

    /**
     * Generated from protobuf field <code>string Pin = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPin($var)
    {
        GPBUtil::checkString($var, True);
        $this->Pin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PushToken = 3;</code>
     * @return string
     */
    public function getPushToken()
    {
        return $this->PushToken;
    }

    /**
     * Generated from protobuf field <code>string PushToken = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPushToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->PushToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OsType = 4;</code>
     * @return string
     */
    public function getOsType()
    {
        return $this->OsType;
    }

    /**
     * Generated from protobuf field <code>string OsType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOsType($var)
    {
        GPBUtil::checkString($var, True);
        $this->OsType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CreatedAt = 5;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->CreatedAt;
    }

    /**
     * Generated from protobuf field <code>string CreatedAt = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->CreatedAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UpdatedAt = 6;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->UpdatedAt;
    }

    /**
     * Generated from protobuf field <code>string UpdatedAt = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->UpdatedAt = $var;

        return $this;
    }

}

