<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Velmie\Wallet\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>velmie.wallet.users.DevicesResponse</code>
 */
class DevicesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.velmie.wallet.users.Device device = 1;</code>
     */
    private $device = null;
    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.users.Device devices = 2;</code>
     */
    private $devices;
    /**
     * Generated from protobuf field <code>.velmie.wallet.users.Error error = 3;</code>
     */
    private $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Velmie\Wallet\Users\Device $device
     *     @type \Velmie\Wallet\Users\Device[]|\Google\Protobuf\Internal\RepeatedField $devices
     *     @type \Velmie\Wallet\Users\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.velmie.wallet.users.Device device = 1;</code>
     * @return \Velmie\Wallet\Users\Device
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     * Generated from protobuf field <code>.velmie.wallet.users.Device device = 1;</code>
     * @param \Velmie\Wallet\Users\Device $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkMessage($var, \Velmie\Wallet\Users\Device::class);
        $this->device = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.users.Device devices = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDevices()
    {
        return $this->devices;
    }

    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.users.Device devices = 2;</code>
     * @param \Velmie\Wallet\Users\Device[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDevices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Velmie\Wallet\Users\Device::class);
        $this->devices = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.velmie.wallet.users.Error error = 3;</code>
     * @return \Velmie\Wallet\Users\Error
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>.velmie.wallet.users.Error error = 3;</code>
     * @param \Velmie\Wallet\Users\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Velmie\Wallet\Users\Error::class);
        $this->error = $var;

        return $this;
    }

}

