<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Velmie\Wallet\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>velmie.wallet.users.FullUsersResponse</code>
 */
class FullUsersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.users.FullUser full_users = 1;</code>
     */
    private $full_users;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Velmie\Wallet\Users\FullUser[]|\Google\Protobuf\Internal\RepeatedField $full_users
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.users.FullUser full_users = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFullUsers()
    {
        return $this->full_users;
    }

    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.users.FullUser full_users = 1;</code>
     * @param \Velmie\Wallet\Users\FullUser[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFullUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Velmie\Wallet\Users\FullUser::class);
        $this->full_users = $arr;

        return $this;
    }

}

