<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Velmie\Wallet\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>velmie.wallet.users.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string UID = 1;</code>
     */
    private $UID = '';
    /**
     * Generated from protobuf field <code>string Email = 2;</code>
     */
    private $Email = '';
    /**
     * Generated from protobuf field <code>string Username = 3;</code>
     */
    private $Username = '';
    /**
     * Generated from protobuf field <code>string FirstName = 4;</code>
     */
    private $FirstName = '';
    /**
     * Generated from protobuf field <code>string LastName = 5;</code>
     */
    private $LastName = '';
    /**
     * Generated from protobuf field <code>string RoleName = 6;</code>
     */
    private $RoleName = '';
    /**
     * Generated from protobuf field <code>uint64 GroupId = 7;</code>
     */
    private $GroupId = 0;
    /**
     * Generated from protobuf field <code>string PhoneNumber = 8;</code>
     */
    private $PhoneNumber = '';
    /**
     * Generated from protobuf field <code>string CompanyName = 9;</code>
     */
    private $CompanyName = '';
    /**
     * Generated from protobuf field <code>int64 AdministratorClassId = 10;</code>
     */
    private $AdministratorClassId = 0;
    /**
     * Generated from protobuf field <code>string SmsPhoneNumber = 11;</code>
     */
    private $SmsPhoneNumber = '';
    /**
     * Generated from protobuf field <code>string ParentUID = 12;</code>
     */
    private $ParentUID = '';
    /**
     * Generated from protobuf field <code>uint64 CompanyID = 13;</code>
     */
    private $CompanyID = 0;
    /**
     * Generated from protobuf field <code>bool IsPhoneNumberConfirmed = 14;</code>
     */
    private $IsPhoneNumberConfirmed = false;
    /**
     * Generated from protobuf field <code>bool IsEmailConfirmed = 15;</code>
     */
    private $IsEmailConfirmed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UID
     *     @type string $Email
     *     @type string $Username
     *     @type string $FirstName
     *     @type string $LastName
     *     @type string $RoleName
     *     @type int|string $GroupId
     *     @type string $PhoneNumber
     *     @type string $CompanyName
     *     @type int|string $AdministratorClassId
     *     @type string $SmsPhoneNumber
     *     @type string $ParentUID
     *     @type int|string $CompanyID
     *     @type bool $IsPhoneNumberConfirmed
     *     @type bool $IsEmailConfirmed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string UID = 1;</code>
     * @return string
     */
    public function getUID()
    {
        return $this->UID;
    }

    /**
     * Generated from protobuf field <code>string UID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUID($var)
    {
        GPBUtil::checkString($var, True);
        $this->UID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Email = 2;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->Email;
    }

    /**
     * Generated from protobuf field <code>string Email = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->Email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->Username;
    }

    /**
     * Generated from protobuf field <code>string Username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->Username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FirstName = 4;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->FirstName;
    }

    /**
     * Generated from protobuf field <code>string FirstName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FirstName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LastName = 5;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->LastName;
    }

    /**
     * Generated from protobuf field <code>string LastName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RoleName = 6;</code>
     * @return string
     */
    public function getRoleName()
    {
        return $this->RoleName;
    }

    /**
     * Generated from protobuf field <code>string RoleName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleName($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoleName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 GroupId = 7;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->GroupId;
    }

    /**
     * Generated from protobuf field <code>uint64 GroupId = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkUint64($var);
        $this->GroupId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PhoneNumber = 8;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->PhoneNumber;
    }

    /**
     * Generated from protobuf field <code>string PhoneNumber = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->PhoneNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CompanyName = 9;</code>
     * @return string
     */
    public function getCompanyName()
    {
        return $this->CompanyName;
    }

    /**
     * Generated from protobuf field <code>string CompanyName = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->CompanyName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 AdministratorClassId = 10;</code>
     * @return int|string
     */
    public function getAdministratorClassId()
    {
        return $this->AdministratorClassId;
    }

    /**
     * Generated from protobuf field <code>int64 AdministratorClassId = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAdministratorClassId($var)
    {
        GPBUtil::checkInt64($var);
        $this->AdministratorClassId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SmsPhoneNumber = 11;</code>
     * @return string
     */
    public function getSmsPhoneNumber()
    {
        return $this->SmsPhoneNumber;
    }

    /**
     * Generated from protobuf field <code>string SmsPhoneNumber = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSmsPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->SmsPhoneNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ParentUID = 12;</code>
     * @return string
     */
    public function getParentUID()
    {
        return $this->ParentUID;
    }

    /**
     * Generated from protobuf field <code>string ParentUID = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setParentUID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentUID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 CompanyID = 13;</code>
     * @return int|string
     */
    public function getCompanyID()
    {
        return $this->CompanyID;
    }

    /**
     * Generated from protobuf field <code>uint64 CompanyID = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyID($var)
    {
        GPBUtil::checkUint64($var);
        $this->CompanyID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsPhoneNumberConfirmed = 14;</code>
     * @return bool
     */
    public function getIsPhoneNumberConfirmed()
    {
        return $this->IsPhoneNumberConfirmed;
    }

    /**
     * Generated from protobuf field <code>bool IsPhoneNumberConfirmed = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPhoneNumberConfirmed($var)
    {
        GPBUtil::checkBool($var);
        $this->IsPhoneNumberConfirmed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsEmailConfirmed = 15;</code>
     * @return bool
     */
    public function getIsEmailConfirmed()
    {
        return $this->IsEmailConfirmed;
    }

    /**
     * Generated from protobuf field <code>bool IsEmailConfirmed = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEmailConfirmed($var)
    {
        GPBUtil::checkBool($var);
        $this->IsEmailConfirmed = $var;

        return $this;
    }

}

