<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Velmie\Wallet\Users;

use Twirp\Error;

/**
 *
 *
 * Generated from protobuf service <code>velmie.wallet.users.UserHandler</code>
 */
interface UserHandler
{
    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByUID</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetByUID(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByUsername</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetByUsername(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByProfileData</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetByProfileData(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByRoleName</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetByRoleName(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/ValidateAccessToken</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function ValidateAccessToken(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByUIDs</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetByUIDs(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByUserGroupId</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetByUserGroupId(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetAll</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetAll(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetFullUsersByUIDs</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\RequestFullUsersByUIDs $req
     *
     * @return \Velmie\Wallet\Users\FullUsersResponse
     *
     * @throws Error
     */
    public function GetFullUsersByUIDs(array $ctx, \Velmie\Wallet\Users\RequestFullUsersByUIDs $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetDevicesByUID</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\DevicesRequest $req
     *
     * @return \Velmie\Wallet\Users\DevicesResponse
     *
     * @throws Error
     */
    public function GetDevicesByUID(array $ctx, \Velmie\Wallet\Users\DevicesRequest $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByAdministratorClassId</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetByAdministratorClassId(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/ValidateTmpAuthToken</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function ValidateTmpAuthToken(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetStaffUsers</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\Request $req
     *
     * @return \Velmie\Wallet\Users\Response
     *
     * @throws Error
     */
    public function GetStaffUsers(array $ctx, \Velmie\Wallet\Users\Request $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetCompaniesByIDs</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\CompaniesIDsRequest $req
     *
     * @return \Velmie\Wallet\Users\CompaniesResponse
     *
     * @throws Error
     */
    public function GetCompaniesByIDs(array $ctx, \Velmie\Wallet\Users\CompaniesIDsRequest $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/SaveCompaniesByName</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\CompaniesNameRequest $req
     *
     * @return \Velmie\Wallet\Users\CompaniesResponse
     *
     * @throws Error
     */
    public function SaveCompaniesByName(array $ctx, \Velmie\Wallet\Users\CompaniesNameRequest $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/UpdateUserAndAttributes</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\UserUpdateRequest $req
     *
     * @return \Velmie\Wallet\Users\UserUpdateResponse
     *
     * @throws Error
     */
    public function UpdateUserAndAttributes(array $ctx, \Velmie\Wallet\Users\UserUpdateRequest $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetUserAndAttributes</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Users\UserGetRequest $req
     *
     * @return \Velmie\Wallet\Users\UserGetResponse
     *
     * @throws Error
     */
    public function GetUserAndAttributes(array $ctx, \Velmie\Wallet\Users\UserGetRequest $req);
}
