<?php
# Generated by the protocol buffer compiler (protoc-gen-twirp_php ).  DO NOT EDIT!
# source: users.proto

declare(strict_types=1);

namespace Velmie\Wallet\Users;

use Google\Protobuf\Internal\GPBDecodeException;
use Google\Protobuf\Internal\Message;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Twirp\Context;
use Twirp\Error;
use Twirp\ErrorCode;

/**
 * A Protobuf client that implements the {@see UserHandler} interface.
 * It communicates using Protobuf and can be configured with a custom HTTP Client.
 *
 * Generated from protobuf service <code>velmie.wallet.users.UserHandler</code>
 */
final class UserHandlerClient implements UserHandler
{
    /**
     * @var server
     */
    private $addr;

    /**
     * @var ClientInterface
     */
    private $httpClient;

    /**
     * @var RequestFactoryInterface
     */
    private $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    private $streamFactory;

    public function __construct(
        $addr,
        ClientInterface $httpClient = null,
        RequestFactoryInterface $requestFactory = null,
        StreamFactoryInterface $streamFactory = null
    ) {
        if ($httpClient === null) {
            $httpClient = Psr18ClientDiscovery::find();
        }

        if ($requestFactory === null) {
            $requestFactory = Psr17FactoryDiscovery::findRequestFactory();
        }

        if ($streamFactory === null) {
            $streamFactory = Psr17FactoryDiscovery::findStreamFactory();
        }

        $this->addr = $this->urlBase($addr);
        $this->httpClient = $httpClient;
        $this->requestFactory = $requestFactory;
        $this->streamFactory = $streamFactory;
    }

/**
     * {@inheritdoc}
     */
    public function GetByUID(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetByUID');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetByUID';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetByUsername(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetByUsername');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetByUsername';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetByProfileData(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetByProfileData');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetByProfileData';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetByRoleName(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetByRoleName');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetByRoleName';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function ValidateAccessToken(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'ValidateAccessToken');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/ValidateAccessToken';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetByUIDs(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetByUIDs');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetByUIDs';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetByUserGroupId(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetByUserGroupId');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetByUserGroupId';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetAll(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetAll');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetAll';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetFullUsersByUIDs(array $ctx, \Velmie\Wallet\Users\RequestFullUsersByUIDs $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetFullUsersByUIDs');

        $out = new \Velmie\Wallet\Users\FullUsersResponse();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetFullUsersByUIDs';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetDevicesByUID(array $ctx, \Velmie\Wallet\Users\DevicesRequest $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetDevicesByUID');

        $out = new \Velmie\Wallet\Users\DevicesResponse();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetDevicesByUID';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetByAdministratorClassId(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetByAdministratorClassId');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetByAdministratorClassId';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function ValidateTmpAuthToken(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'ValidateTmpAuthToken');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/ValidateTmpAuthToken';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetStaffUsers(array $ctx, \Velmie\Wallet\Users\Request $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetStaffUsers');

        $out = new \Velmie\Wallet\Users\Response();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetStaffUsers';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetCompaniesByIDs(array $ctx, \Velmie\Wallet\Users\CompaniesIDsRequest $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetCompaniesByIDs');

        $out = new \Velmie\Wallet\Users\CompaniesResponse();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetCompaniesByIDs';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function SaveCompaniesByName(array $ctx, \Velmie\Wallet\Users\CompaniesNameRequest $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'SaveCompaniesByName');

        $out = new \Velmie\Wallet\Users\CompaniesResponse();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/SaveCompaniesByName';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function UpdateUserAndAttributes(array $ctx, \Velmie\Wallet\Users\UserUpdateRequest $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'UpdateUserAndAttributes');

        $out = new \Velmie\Wallet\Users\UserUpdateResponse();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/UpdateUserAndAttributes';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * {@inheritdoc}
     */
    public function GetUserAndAttributes(array $ctx, \Velmie\Wallet\Users\UserGetRequest $in)
    {
        $ctx = Context::withPackageName($ctx, 'velmie.wallet.users');
        $ctx = Context::withServiceName($ctx, 'UserHandler');
        $ctx = Context::withMethodName($ctx, 'GetUserAndAttributes');

        $out = new \Velmie\Wallet\Users\UserGetResponse();

        $url = $this->addr.'/twirp/velmie.wallet.users.UserHandler/GetUserAndAttributes';

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }

    /**
     * Common code to make a request to the remote twirp service.
     */
    private function doProtobufRequest(array $ctx, string $url, Message $in, Message $out): void
    {
        $body = $in->serializeToString();

        $req = $this->newRequest($ctx, $url, $body, 'application/protobuf');

        try {
            $resp = $this->httpClient->sendRequest($req);
        } catch (\Throwable $e) {
            throw $this->clientError('failed to send request', $e);
        }

        if ($resp->getStatusCode() !== 200) {
            throw $this->errorFromResponse($resp);
        }

        try {
            $out->mergeFromString((string)$resp->getBody());
        } catch (GPBDecodeException $e) {
            throw $this->clientError('failed to unmarshal proto response', $e);
        }
    }

    /**
     * Makes an HTTP request and adds common headers.
     */
    private function newRequest(array $ctx, string $url, string $reqBody, string $contentType): RequestInterface
    {
        $body = $this->streamFactory->createStream($reqBody);

        $req = $this->requestFactory->createRequest('POST', $url);

        $headers = Context::httpRequestHeaders($ctx);

        foreach ($headers as $key => $value) {
            $req = $req->withHeader($key, $value);
        }

        return $req
            ->withBody($body)
            ->withHeader('Accept', $contentType)
            ->withHeader('Content-Type', $contentType)
            ->withHeader('Twirp-Version', 'v5.3.0');
    }

    /**
     * Adds consistency to errors generated in the client.
     */
    private function clientError(string $desc, \Throwable $e): TwirpError
    {
        return TwirpError::newError(ErrorCode::Internal, sprintf('%s: %s', $desc, $e->getMessage()));
    }

    /**
     * Builds a twirp Error from a non-200 HTTP response.
     * If the response has a valid serialized Twirp error, then it's returned.
     * If not, the response status code is used to generate a similar twirp
     * error. {@see self::twirpErrorFromIntermediary} for more info on intermediary errors.
     */
    private function errorFromResponse(ResponseInterface $resp): TwirpError
    {
        $statusCode = $resp->getStatusCode();
        $statusText = $resp->getReasonPhrase();

        if ($this->isHttpRedirect($statusCode)) {
            // Unexpected redirect: it must be an error from an intermediary.
            // Twirp clients don't follow redirects automatically, Twirp only handles
            // POST requests, redirects should only happen on GET and HEAD requests.
            $location = $resp->getHeaderLine('Location');
            $msg = sprintf(
                'unexpected HTTP status code %d "%s" received, Location="%s"',
                $statusCode,
                $statusText,
                $location
            );

            return $this->twirpErrorFromIntermediary($statusCode, $msg, $location);
        }

        $body = (string)$resp->getBody();

        $rawError = json_decode($body, true);
        if ($rawError === null) {
            $msg = sprintf('error from intermediary with HTTP status code %d "%s"', $statusCode, $statusText);

            return $this->twirpErrorFromIntermediary($statusCode, $msg, $body);
        }

        $rawError = $rawError + ['code' => '', 'msg' => '', 'meta' => []];

        if (ErrorCode::isValid($rawError['code']) === false) {
            $msg = 'invalid type returned from server error response: '.$rawError['code'];

            return TwirpError::newError(ErrorCode::Internal, $msg);
        }

        $error = TwirpError::newError($rawError['code'], $rawError['msg']);

        foreach ($rawError['meta'] as $key => $value) {
           $error->setMeta($key, $value);
        }

        return $error;
    }

    /**
     * Maps HTTP errors from non-twirp sources to twirp errors.
     * The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
     * Returned twirp Errors have some additional metadata for inspection.
     */
    private function twirpErrorFromIntermediary(int $status, string $msg, string $bodyOrLocation): TwirpError
    {
        if ($this->isHttpRedirect($status)) {
            $code = ErrorCode::Internal;
        } else {
            switch ($status) {
                case 400: // Bad Request
                    $code = ErrorCode::Internal;
                    break;
                case 401: // Unauthorized
                    $code = ErrorCode::Unauthenticated;
                    break;
                case 403: // Forbidden
                    $code = ErrorCode::PermissionDenied;
                    break;
                case 404: // Not Found
                    $code = ErrorCode::BadRoute;
                    break;
                case 429: // Too Many Requests
                case 502: // Bad Gateway
                case 503: // Service Unavailable
                case 504: // Gateway Timeout
                    $code = ErrorCode::Unavailable;
                    break;
                default: // All other codes
                    $code = ErrorCode::Unknown;
                    break;
            }
        }

        $error = TwirpError::newError($code, $msg);
        $error->setMeta('http_error_from_intermediary', 'true');
        $error->setMeta('status_code', (string)$status);

        if ($this->isHttpRedirect($status)) {
            $error->setMeta('location', $bodyOrLocation);
        } else {
            $error->setMeta('body', $bodyOrLocation);
        }

        return $error;
    }

    private function isHttpRedirect(int $status): bool
    {
        return $status >= 300 && $status <= 399;
    }

    private function urlBase(string $addr): string
    {
        $scheme = parse_url($addr, PHP_URL_SCHEME);

        // If parse_url fails, return the addr unchanged.
        if ($scheme === false) {
            return $addr;
        }

        // If the addr does not specify a scheme, default to http.
        if (empty($scheme)) {
            $addr = 'http://'.ltrim($addr, ':/');
        }

        return $addr;
    }
}