<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Velmie\Wallet\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>velmie.wallet.users.UserDetails</code>
 */
class UserDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string class_id = 1;</code>
     */
    private $class_id = '';
    /**
     * Generated from protobuf field <code>string country_of_residence_iso2 = 2;</code>
     */
    private $country_of_residence_iso2 = '';
    /**
     * Generated from protobuf field <code>string country_of_citizenship_iso2 = 3;</code>
     */
    private $country_of_citizenship_iso2 = '';
    /**
     * Generated from protobuf field <code>uint64 date_of_birth_year = 4;</code>
     */
    private $date_of_birth_year = 0;
    /**
     * Generated from protobuf field <code>uint64 date_of_birth_month = 5;</code>
     */
    private $date_of_birth_month = 0;
    /**
     * Generated from protobuf field <code>uint64 date_of_birth_day = 6;</code>
     */
    private $date_of_birth_day = 0;
    /**
     * Generated from protobuf field <code>string document_type = 7;</code>
     */
    private $document_type = '';
    /**
     * Generated from protobuf field <code>string document_personal_id = 8;</code>
     */
    private $document_personal_id = '';
    /**
     * Generated from protobuf field <code>string fax = 9;</code>
     */
    private $fax = '';
    /**
     * Generated from protobuf field <code>string home_phone_number = 10;</code>
     */
    private $home_phone_number = '';
    /**
     * Generated from protobuf field <code>string internal_notes = 11;</code>
     */
    private $internal_notes = '';
    /**
     * Generated from protobuf field <code>string office_phone_number = 12;</code>
     */
    private $office_phone_number = '';
    /**
     * Generated from protobuf field <code>string position = 13;</code>
     */
    private $position = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $class_id
     *     @type string $country_of_residence_iso2
     *     @type string $country_of_citizenship_iso2
     *     @type int|string $date_of_birth_year
     *     @type int|string $date_of_birth_month
     *     @type int|string $date_of_birth_day
     *     @type string $document_type
     *     @type string $document_personal_id
     *     @type string $fax
     *     @type string $home_phone_number
     *     @type string $internal_notes
     *     @type string $office_phone_number
     *     @type string $position
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string class_id = 1;</code>
     * @return string
     */
    public function getClassId()
    {
        return $this->class_id;
    }

    /**
     * Generated from protobuf field <code>string class_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkString($var, True);
        $this->class_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country_of_residence_iso2 = 2;</code>
     * @return string
     */
    public function getCountryOfResidenceIso2()
    {
        return $this->country_of_residence_iso2;
    }

    /**
     * Generated from protobuf field <code>string country_of_residence_iso2 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryOfResidenceIso2($var)
    {
        GPBUtil::checkString($var, True);
        $this->country_of_residence_iso2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country_of_citizenship_iso2 = 3;</code>
     * @return string
     */
    public function getCountryOfCitizenshipIso2()
    {
        return $this->country_of_citizenship_iso2;
    }

    /**
     * Generated from protobuf field <code>string country_of_citizenship_iso2 = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryOfCitizenshipIso2($var)
    {
        GPBUtil::checkString($var, True);
        $this->country_of_citizenship_iso2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 date_of_birth_year = 4;</code>
     * @return int|string
     */
    public function getDateOfBirthYear()
    {
        return $this->date_of_birth_year;
    }

    /**
     * Generated from protobuf field <code>uint64 date_of_birth_year = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDateOfBirthYear($var)
    {
        GPBUtil::checkUint64($var);
        $this->date_of_birth_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 date_of_birth_month = 5;</code>
     * @return int|string
     */
    public function getDateOfBirthMonth()
    {
        return $this->date_of_birth_month;
    }

    /**
     * Generated from protobuf field <code>uint64 date_of_birth_month = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDateOfBirthMonth($var)
    {
        GPBUtil::checkUint64($var);
        $this->date_of_birth_month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 date_of_birth_day = 6;</code>
     * @return int|string
     */
    public function getDateOfBirthDay()
    {
        return $this->date_of_birth_day;
    }

    /**
     * Generated from protobuf field <code>uint64 date_of_birth_day = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDateOfBirthDay($var)
    {
        GPBUtil::checkUint64($var);
        $this->date_of_birth_day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string document_type = 7;</code>
     * @return string
     */
    public function getDocumentType()
    {
        return $this->document_type;
    }

    /**
     * Generated from protobuf field <code>string document_type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->document_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string document_personal_id = 8;</code>
     * @return string
     */
    public function getDocumentPersonalId()
    {
        return $this->document_personal_id;
    }

    /**
     * Generated from protobuf field <code>string document_personal_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentPersonalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->document_personal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fax = 9;</code>
     * @return string
     */
    public function getFax()
    {
        return $this->fax;
    }

    /**
     * Generated from protobuf field <code>string fax = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFax($var)
    {
        GPBUtil::checkString($var, True);
        $this->fax = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string home_phone_number = 10;</code>
     * @return string
     */
    public function getHomePhoneNumber()
    {
        return $this->home_phone_number;
    }

    /**
     * Generated from protobuf field <code>string home_phone_number = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setHomePhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->home_phone_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string internal_notes = 11;</code>
     * @return string
     */
    public function getInternalNotes()
    {
        return $this->internal_notes;
    }

    /**
     * Generated from protobuf field <code>string internal_notes = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setInternalNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->internal_notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string office_phone_number = 12;</code>
     * @return string
     */
    public function getOfficePhoneNumber()
    {
        return $this->office_phone_number;
    }

    /**
     * Generated from protobuf field <code>string office_phone_number = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setOfficePhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->office_phone_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string position = 13;</code>
     * @return string
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>string position = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkString($var, True);
        $this->position = $var;

        return $this;
    }

}

