<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissions.proto

namespace Velmie\Wallet\Permissions;

use Twirp\Error;

/**
 *
 *
 * Generated from protobuf service <code>velmie.wallet.permissions.PermissionChecker</code>
 */
interface PermissionChecker
{
    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.permissions.PermissionChecker/Check</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Permissions\PermissionReq $req
     *
     * @return \Velmie\Wallet\Permissions\PermissionResp
     *
     * @throws Error
     */
    public function Check(array $ctx, \Velmie\Wallet\Permissions\PermissionReq $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.permissions.PermissionChecker/CheckAll</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Permissions\PermissionsReq $req
     *
     * @return \Velmie\Wallet\Permissions\PermissionsResp
     *
     * @throws Error
     */
    public function CheckAll(array $ctx, \Velmie\Wallet\Permissions\PermissionsReq $req);

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.permissions.PermissionChecker/GetGroupsByIds</code>
     *
     * @param array $ctx
     * @param \Velmie\Wallet\Permissions\GroupIdsReq $req
     *
     * @return \Velmie\Wallet\Permissions\GroupsResponse
     *
     * @throws Error
     */
    public function GetGroupsByIds(array $ctx, \Velmie\Wallet\Permissions\GroupIdsReq $req);
}
