<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissions.proto

namespace Velmie\Wallet\Permissions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>velmie.wallet.permissions.PermissionResp</code>
 */
class PermissionResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    private $user_id = '';
    /**
     * Generated from protobuf field <code>string action_key = 2;</code>
     */
    private $action_key = '';
    /**
     * Generated from protobuf field <code>bool is_allowed = 3;</code>
     */
    private $is_allowed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $action_key
     *     @type bool $is_allowed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Permissions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action_key = 2;</code>
     * @return string
     */
    public function getActionKey()
    {
        return $this->action_key;
    }

    /**
     * Generated from protobuf field <code>string action_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setActionKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->action_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_allowed = 3;</code>
     * @return bool
     */
    public function getIsAllowed()
    {
        return $this->is_allowed;
    }

    /**
     * Generated from protobuf field <code>bool is_allowed = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAllowed($var)
    {
        GPBUtil::checkBool($var);
        $this->is_allowed = $var;

        return $this;
    }

}

